# Generated by Django 6.1 on 2026-08-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_apellido_comprador_pedido_calle_pedido_comuna_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
